### ISSUE TITLE
question

### ISSUE THREAD

**Issue by iplayfast** [SebLague/Hydraulic-Erosion#3]
I'm new to c# and am running from linux using monodevelop. Should there be a project file of some sort here? Sorry for the newb question.

**Comment by Anticom** [comment]
@iplayfast It's a unity project and according to https://store.unity.com/download?ref=personal it is only available for Windows and OSX.
You might be able to run some of the sources on mono but i don't think you're going to get much out of it.

**Comment by kaskii** [comment]
@iplayfast This project needs Unity engine. Linux version of Unity engine is available in the Unity forums https://forum.unity.com/threads/unity-on-linux-release-notes-and-known-issues.350256/page-2#post-4458286

Please note that Linux build is in beta.
