### ISSUE TITLE
Getting error CS1644: Feature 'interpolated strings' cannot be used.

### ISSUE THREAD

**Issue by nicholascc** [SebLague/Hydraulic-Erosion#4]
I'm getting the following error at load. How might I fix this so that I can run the program?

Assets/Editor/MeshEditor.cs(40,28): error CS1644: Feature `interpolated strings' cannot be used because it is not part of the C# 4.0 language specification.

It seems like I'm not using the right C# version or something?

**Comment by nicholascc** [comment]
Hey @SebLague any answers?

**Comment by natiiix** [comment]
@nicholas-2 The error message suggests an outdated .NET SDK or something along those lines. C# 4.0 is already pretty old considering C# 7.0 has been out for about 2 years.

I'm not sure how far the compatibility between Unity and more recent versions of .NET and C# goes, but I believe it should support fairly recent C# versions, perhaps even C# 7.0.

By the way, interpolated strings are the ones looking something like this: `$"Regular text {variable} some more text {expression} even more text"` as far as I know. So you should be easily able to replace them with regular strings.

**Comment by Aoost** [comment]
Does this work in the new LWRP?
