### ISSUE TITLE
Error "Thread group count is above the maximum allowed limit. Maximum allowed thread group count is 65535."

### ISSUE THREAD

**Issue by hayes87** [SebLague/Hydraulic-Erosion#5]
Im getting this error when building the terrain
"Thread group count is above the maximum allowed limit. Maximum allowed thread group count is 65535."

**Comment by VSMent** [comment]
@hayes87 how did you manage to solve it?

**Comment by VSMent** [comment]
Figured out.
There are two options as far as I understand
Decrease `TerrainGenerator : mapSize` / `TerrainGenerator : erosionBrushRadius`
or disable `HeightMapGenerator : useComputeShader`

**Comment by marwie** [comment]
You can also just change numthreads from ``[numthreads(1,1,1)]`` to ``[numthreads(64,1,1)]`` in HeightMap.compute
and then change the dispatch to ``heightMapComputeShader.Dispatch (0, Mathf.CeilToInt(map.Length/64f), 1, 1); `` in HeightMapGenerator:52
